name: login
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  sqflite_common_ffi: any
  path_provider: ^2.0.2
  intl: ^0.17.0

  # Dependencies for Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.0.0


  # Other dependencies
  cupertino_icons: ^1.0.8

  share_plus: ^10.1.4
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter-icons:
  android: true
  ios: true
  windows: true
  image_path: "assets/logoDiario.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logoDiario.png
