// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVlrKEcyIVZ1GlBaLTvOa8YhaagDs3wwY',
    appId: '1:205244634925:web:bcbe308664c5ae5755a5a4',
    messagingSenderId: '205244634925',
    projectId: 'diario-668c7',
    authDomain: 'diario-668c7.firebaseapp.com',
    storageBucket: 'diario-668c7.firebasestorage.app',
    measurementId: 'G-P5M3XDE589',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Dd2z-6qPNCitRcVErsL9QLGFWlU-wps',
    appId: '1:205244634925:android:6936d3af5652033055a5a4',
    messagingSenderId: '205244634925',
    projectId: 'diario-668c7',
    storageBucket: 'diario-668c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYo-yM560KJ0_MClMyUnvxmBg9iEtnr5o',
    appId: '1:205244634925:ios:55becf93b91da44255a5a4',
    messagingSenderId: '205244634925',
    projectId: 'diario-668c7',
    storageBucket: 'diario-668c7.firebasestorage.app',
    iosBundleId: 'com.example.diarioPersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVlrKEcyIVZ1GlBaLTvOa8YhaagDs3wwY',
    appId: '1:205244634925:web:b9a045e4311e004e55a5a4',
    messagingSenderId: '205244634925',
    projectId: 'diario-668c7',
    authDomain: 'diario-668c7.firebaseapp.com',
    storageBucket: 'diario-668c7.firebasestorage.app',
    measurementId: 'G-1GBCEL37T6',
  );
}
